version: "2.4"
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingFederate getting started demo
#-
#-                +---------------+
#-                | PingFederate  |
#-                +---------------+
#-
#- To access PingFederate Console
#-
#-    https://localhost:9999/pingfederate/app
#-
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    # You may need to comment this tmpfs line if you run containers on windows
    tmpfs: /run/secrets
    environment:
       - PF_LDAP_USERNAME=xxx
       - PF_LDAP_PASSWORD=yyy
#      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
#      - SERVER_PROFILE_PATH=getting-started/pingfederate
    env_file:
#      - ${HOME}/.pingidentity/devops
      - pf.env
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet
    volumes:
       - ../server_profiles/pingfederate:/opt/in
       - ../licenses/pingfederate.lic:/opt/in/instance/server/default/conf/pingfederate.lic

networks:
  pingnet:

volumes:
  pingfederate-out:
